### ISSUE TITLE
Add toleration for `uninitialized` to standalone install

### ISSUE THREAD

**Issue by hegerdes** [alex1989hu/kubelet-serving-cert-approver#271]
When you create a new selfmanaged cluster you often add need to add the `cloud-provider=external` arg. This is expected for some cloud providers. It adds the taint `node.cloudprovider.kubernetes.io/uninitialized`, which is only removed when the cloud-controler is done with the node which could take some time. It would be nice if the [standalone-install.yaml](https://github.com/alex1989hu/kubelet-serving-cert-approver/blob/main/deploy/standalone-install.yaml) would have a toleration for this, since to taint does not prevent the node from functioning.

```yaml
      tolerations:
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
```

Otherwise the kubelet will not have a valid cert until all other initial cations are completed. Do you think this is something worth supporting?
